name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        id: build
        run: dotnet build -warnaserror -p:TreatWarningsAsErrors=true -bl:build.binlog

      - name: Incremental re-build
        run: dotnet build -warnaserror -p:TreatWarningsAsErrors=true -question -bl:question.binlog

      - name: Publish server
        if: ${{ steps.build.outcome == 'success' }}
        run: dotnet publish ./src/Server/Server.csproj -c Debug --no-build --no-restore -bl:publish.binlog

      - name: Check BOM changes
        if: always()
        run: dnx bom check pr

      - name: Upload build binaries
        if: ${{ steps.build.outcome == 'success' }}
        uses: actions/upload-artifact@v6
        with:
          name: build-binaries-${{ matrix.os }}
          path: |
            artifacts/bin/**/debug/**
            artifacts/publish/Server/debug/**
          if-no-files-found: error

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: logs-${{ matrix.os }}
          path: |
            *.binlog
            **/TestResults/*.*

  # When using dotnet-watch, we turn off toolset compilers,
  # so make sure the project is buildable without them.
  build-without-toolset-compilers:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: dotnet build -warnaserror -p:TreatWarningsAsErrors=true -p:DotNetLabUseCompilerToolset=false -bl

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: logs-build-without-toolset-compilers
          path: |
            *.binlog
